//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezProje.Models.Siniflar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bilgilendirme
    {
        public int BilgiID { get; set; }
        public string FotoUrl { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
    }
}
