//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezProje.Models.Siniflar
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Harita
    {
        public int HaritaID { get; set; }
        [AllowHtml]
        public string Frame { get; set; }
    }
}
