//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezProje.Models.Siniflar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TatilBlogEntities : DbContext
    {
        public TatilBlogEntities()
            : base("name=TatilBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Hakkimda> Hakkimda { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<KullaniciYazi> KullaniciYazi { get; set; }
        public virtual DbSet<Uye> Uye { get; set; }
        public virtual DbSet<Yorumlar> Yorumlar { get; set; }
        public virtual DbSet<Harita> Harita { get; set; }
        public virtual DbSet<Basliklar> Basliklar { get; set; }
        public virtual DbSet<Bilgilendirme> Bilgilendirme { get; set; }
        public virtual DbSet<KullaniciYorum> KullaniciYorum { get; set; }
        public virtual DbSet<Bulten> Bulten { get; set; }
    }
}
