//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TezProje.Models.Siniflar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int YorumID { get; set; }
        public string KullaniciAdi { get; set; }
        public string Mail { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> BlogID { get; set; }
        public Nullable<bool> Durum { get; set; }
        public Nullable<System.DateTime> YorumTarih { get; set; }
    
        public virtual Blog Blog { get; set; }
    }
}
